# Generated by Django 5.1.1 on 2024-11-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='questions',
            field=models.ManyToManyField(blank=True, to='score_manager.question'),
        ),
    ]
