export * from './api.service';
import { ApiService } from './api.service';
export * from './api.serviceInterface';
export * from './auth.service';
import { AuthService } from './auth.service';
export * from './auth.serviceInterface';
export * from './class.service';
import { ClassService } from './class.service';
export * from './class.serviceInterface';
export * from './config.service';
import { ConfigService } from './config.service';
export * from './config.serviceInterface';
export * from './difficulty.service';
import { DifficultyService } from './difficulty.service';
export * from './difficulty.serviceInterface';
export * from './question.service';
import { QuestionService } from './question.service';
export * from './question.serviceInterface';
export * from './results.service';
import { ResultsService } from './results.service';
export * from './results.serviceInterface';
export * from './student.service';
import { StudentService } from './student.service';
export * from './student.serviceInterface';
export * from './studentresult.service';
import { StudentresultService } from './studentresult.service';
export * from './studentresult.serviceInterface';
export * from './subject.service';
import { SubjectService } from './subject.service';
export * from './subject.serviceInterface';
export * from './test.service';
import { TestService } from './test.service';
export * from './test.serviceInterface';
export const APIS = [ApiService, AuthService, ClassService, ConfigService, DifficultyService, QuestionService, ResultsService, StudentService, StudentresultService, SubjectService, TestService];
