export * from './api.service';
import { ApiService } from './api.service';
export * from './api.serviceInterface';
export * from './auth.service';
import { AuthService } from './auth.service';
export * from './auth.serviceInterface';
export * from './difficulty.service';
import { DifficultyService } from './difficulty.service';
export * from './difficulty.serviceInterface';
export * from './question.service';
import { QuestionService } from './question.service';
export * from './question.serviceInterface';
export * from './setting.service';
import { SettingService } from './setting.service';
export * from './setting.serviceInterface';
export * from './test.service';
import { TestService } from './test.service';
export * from './test.serviceInterface';
export const APIS = [ApiService, AuthService, DifficultyService, QuestionService, SettingService, TestService];
