/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ConfigUpdate200Response } from '../model/models';
import { ConfigUpdate400Response } from '../model/models';
import { ConfigUpdateRequestInner } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ConfigServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Retrieve configuration settings
     * Fetches all configuration settings as a key-value dictionary.
     */
    configRetrieve(extraHttpRequestParams?: any): Observable<{ [key: string]: string; }>;

    /**
     * Update configuration settings
     * Accepts a list of key-value pairs to update the configuration settings. Each item in the list must be a dictionary containing a &#x60;key&#x60; and &#x60;value&#x60;. Invalid keys will result in a 400 response with details about the errors.
     * @param configUpdateRequestInner 
     */
    configUpdate(configUpdateRequestInner?: Array<ConfigUpdateRequestInner>, extraHttpRequestParams?: any): Observable<ConfigUpdate200Response>;

}
