/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { PatchedPermission } from '../model/models';
import { Permission } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface PermissionServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param permission 
     */
    permissionCreate(permission: Permission, extraHttpRequestParams?: any): Observable<Permission>;

    /**
     * 
     * 
     * @param id A unique integer value identifying this permission.
     */
    permissionDestroy(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param ordering Which field to use when ordering the results.
     * @param search A search term.
     */
    permissionList(ordering?: string, search?: string, extraHttpRequestParams?: any): Observable<Array<Permission>>;

    /**
     * 
     * 
     * @param id A unique integer value identifying this permission.
     * @param patchedPermission 
     */
    permissionPartialUpdate(id: number, patchedPermission?: PatchedPermission, extraHttpRequestParams?: any): Observable<Permission>;

    /**
     * 
     * 
     * @param id A unique integer value identifying this permission.
     */
    permissionRetrieve(id: number, extraHttpRequestParams?: any): Observable<Permission>;

    /**
     * 
     * 
     * @param id A unique integer value identifying this permission.
     * @param permission 
     */
    permissionUpdate(id: number, permission: Permission, extraHttpRequestParams?: any): Observable<Permission>;

}
