/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { PaginatedQuestionList } from '../model/models';
import { PatchedQuestion } from '../model/models';
import { Question } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface QuestionServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param question 
     */
    questionCreate(question: Question, extraHttpRequestParams?: any): Observable<Question>;

    /**
     * 
     * 
     * @param id A unique integer value identifying this Question.
     */
    questionDestroy(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param limit Number of results to return per page.
     * @param offset The initial index from which to return the results.
     * @param ordering Which field to use when ordering the results.
     * @param search A search term.
     */
    questionList(limit?: number, offset?: number, ordering?: string, search?: string, extraHttpRequestParams?: any): Observable<PaginatedQuestionList>;

    /**
     * 
     * 
     * @param id A unique integer value identifying this Question.
     * @param patchedQuestion 
     */
    questionPartialUpdate(id: number, patchedQuestion?: PatchedQuestion, extraHttpRequestParams?: any): Observable<Question>;

    /**
     * 
     * 
     * @param id A unique integer value identifying this Question.
     */
    questionRetrieve(id: number, extraHttpRequestParams?: any): Observable<Question>;

    /**
     * 
     * 
     * @param id A unique integer value identifying this Question.
     * @param question 
     */
    questionUpdate(id: number, question: Question, extraHttpRequestParams?: any): Observable<Question>;

}
