/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { PatchedQuestion } from '../model/models';
import { Question } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface QuestionServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param question 
     */
    questionCreate(question: Question, extraHttpRequestParams?: any): Observable<Question>;

    /**
     * 
     * 
     * @param id A unique integer value identifying this Question.
     */
    questionDestroy(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    questionList(extraHttpRequestParams?: any): Observable<Array<Question>>;

    /**
     * 
     * 
     * @param id A unique integer value identifying this Question.
     * @param patchedQuestion 
     */
    questionPartialUpdate(id: number, patchedQuestion?: PatchedQuestion, extraHttpRequestParams?: any): Observable<Question>;

    /**
     * 
     * 
     * @param id A unique integer value identifying this Question.
     */
    questionRetrieve(id: number, extraHttpRequestParams?: any): Observable<Question>;

    /**
     * 
     * 
     * @param id A unique integer value identifying this Question.
     * @param question 
     */
    questionUpdate(id: number, question: Question, extraHttpRequestParams?: any): Observable<Question>;

}
