/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { PatchedRole } from '../model/models';
import { Role } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface RoleServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param role 
     */
    roleCreate(role: Role, extraHttpRequestParams?: any): Observable<Role>;

    /**
     * 
     * 
     * @param id A unique integer value identifying this role.
     */
    roleDestroy(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param ordering Which field to use when ordering the results.
     * @param search A search term.
     */
    roleList(ordering?: string, search?: string, extraHttpRequestParams?: any): Observable<Array<Role>>;

    /**
     * 
     * 
     * @param id A unique integer value identifying this role.
     * @param patchedRole 
     */
    rolePartialUpdate(id: number, patchedRole?: PatchedRole, extraHttpRequestParams?: any): Observable<Role>;

    /**
     * 
     * 
     * @param id A unique integer value identifying this role.
     */
    roleRetrieve(id: number, extraHttpRequestParams?: any): Observable<Role>;

    /**
     * 
     * 
     * @param id A unique integer value identifying this role.
     * @param role 
     */
    roleUpdate(id: number, role: Role, extraHttpRequestParams?: any): Observable<Role>;

}
