/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { PaginatedStudentResultList } from '../model/models';
import { PatchedStudentResult } from '../model/models';
import { StudentResult } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface StudentresultServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param studentResult 
     */
    studentresultCreate(studentResult: StudentResult, extraHttpRequestParams?: any): Observable<StudentResult>;

    /**
     * 
     * 
     * @param id A unique integer value identifying this student result.
     */
    studentresultDestroy(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param limit Number of results to return per page.
     * @param offset The initial index from which to return the results.
     * @param ordering Which field to use when ordering the results.
     */
    studentresultList(limit?: number, offset?: number, ordering?: string, extraHttpRequestParams?: any): Observable<PaginatedStudentResultList>;

    /**
     * 
     * 
     * @param id A unique integer value identifying this student result.
     * @param patchedStudentResult 
     */
    studentresultPartialUpdate(id: number, patchedStudentResult?: PatchedStudentResult, extraHttpRequestParams?: any): Observable<StudentResult>;

    /**
     * 
     * 
     * @param id A unique integer value identifying this student result.
     */
    studentresultRetrieve(id: number, extraHttpRequestParams?: any): Observable<StudentResult>;

    /**
     * 
     * 
     * @param id A unique integer value identifying this student result.
     * @param studentResult 
     */
    studentresultUpdate(id: number, studentResult: StudentResult, extraHttpRequestParams?: any): Observable<StudentResult>;

}
