/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { SummaryRetrieve200Response } from '../model/models';
import { SummaryRetrieve400Response } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface SummaryServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Retrieve yearly statistics for tests and results
     * Fetches total tests and total results for a given year. Additionally, the statistics are grouped by subjects with their respective totals, including the ratio of tests and results for each subject.
     * @param year The year to retrieve statistics for (e.g., 2023).
     */
    summaryRetrieve(year: number, extraHttpRequestParams?: any): Observable<SummaryRetrieve200Response>;

}
