/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { PaginatedUserList } from '../model/models';
import { PatchedUser } from '../model/models';
import { User } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface UserServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param user 
     */
    userCreate(user: User, extraHttpRequestParams?: any): Observable<User>;

    /**
     * 
     * 
     * @param id A unique integer value identifying this user.
     */
    userDestroy(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param limit Number of results to return per page.
     * @param offset The initial index from which to return the results.
     * @param ordering Which field to use when ordering the results.
     * @param search A search term.
     */
    userList(limit?: number, offset?: number, ordering?: string, search?: string, extraHttpRequestParams?: any): Observable<PaginatedUserList>;

    /**
     * 
     * 
     * @param id A unique integer value identifying this user.
     * @param patchedUser 
     */
    userPartialUpdate(id: number, patchedUser?: PatchedUser, extraHttpRequestParams?: any): Observable<User>;

    /**
     * 
     * 
     * @param id A unique integer value identifying this user.
     */
    userRetrieve(id: number, extraHttpRequestParams?: any): Observable<User>;

    /**
     * 
     * 
     * @param id A unique integer value identifying this user.
     * @param user 
     */
    userUpdate(id: number, user: User, extraHttpRequestParams?: any): Observable<User>;

}
