/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ConfigUpdateRequestInner { 
    /**
     * The name of the configuration setting to update.
     */
    key: string;
    /**
     * The new value for the configuration setting.
     */
    value: string;
}

