/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserDetails } from './user-details';


/**
 * Serializer for JWT authentication.
 */
export interface JWT { 
    access: string;
    refresh: string;
    user: UserDetails;
}

