/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Difficulty } from './difficulty';


export interface PaginatedDifficultyList { 
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<Difficulty>;
}

