/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Test } from './test';


export interface PaginatedTestList { 
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<Test>;
}

