/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Teacher } from './teacher';


export interface PaginatedTeacherList { 
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<Teacher>;
}

