/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Student } from './student';


export interface PaginatedStudentList { 
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<Student>;
}

