/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Question } from './question';


export interface PaginatedQuestionList { 
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<Question>;
}

