/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Serializer for confirming a password reset attempt.
 */
export interface PasswordResetConfirm { 
    new_password1: string;
    new_password2: string;
    uid: string;
    token: string;
}

