/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PatchedTest { 
    readonly id?: number;
    readonly questions?: string;
    semester?: number;
    datetime?: string;
    duration?: string;
    readonly created_at?: string;
    readonly updated_at?: string;
    subject?: number;
}

