/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PatchedRole { 
    name?: string;
    description?: string | null;
    permissions?: Array<string>;
    readonly id?: number;
}

