/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PatchedStudent { 
    readonly id?: number;
    name?: string;
    student_code?: string;
    readonly created_at?: string;
    readonly updated_at?: string;
}

