/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PatchedQuestion { 
    readonly id?: number;
    detail?: string | null;
    difficulty?: number;
    subject?: number;
}

