/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Question { 
    readonly id: number;
    detail?: string | null;
    readonly created_at: string;
    readonly updated_at: string;
    difficulty: number;
    subject: number;
}

