/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StudentList200ResponseResultsInner } from './student-list200-response-results-inner';


export interface StudentList200Response { 
    count: number;
    next?: string | null;
    previous?: string | null;
    results: Array<StudentList200ResponseResultsInner>;
}

