/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SummaryRetrieve200ResponseSubjectsInner { 
    name?: string;
    total_tests?: number;
    total_results?: number;
    test_ratio?: number;
    result_ratio?: number;
}

