/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SummaryRetrieve200ResponseSubjectsInner } from './summary-retrieve200-response-subjects-inner';


export interface SummaryRetrieve200Response { 
    total_tests?: number;
    total_results?: number;
    subjects?: Array<SummaryRetrieve200ResponseSubjectsInner>;
}

