/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Question } from './question';


export interface Test { 
    readonly id: number;
    readonly questions: Array<Question>;
    semester: number;
    datetime: string;
    duration: string;
    subject: number;
}

