/**
 * 
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `admin` - admin * `staff` - staff * `user` - user
 */
export type UserTypeEnum = 'admin' | 'staff' | 'user';

export const UserTypeEnum = {
    Admin: 'admin' as UserTypeEnum,
    Staff: 'staff' as UserTypeEnum,
    User: 'user' as UserTypeEnum
};

