name: Pulumi
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

jobs:
  up:
    name: Preview
    runs-on: ubuntu-latest
    environment: Deployment
    defaults:
      run:
        working-directory: infrastructure
    steps:

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: npm install
        run: npm install

      - uses: pulumi/actions@v4
        with:
          command: up
          stack-name: prod

