name: Django CI

on:
  push:
    branches: [ "main" ]
    paths: ["backend/**"]
  pull_request:
    branches: [ "main" ]
    paths: ["backend/**"]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.10']
    defaults:
      run:
        working-directory: ./backend

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
    - name: Setup database
      run: |
        python manage.py migrate
        python manage.py initsuperuser
        python manage.py seed
    - name: Run Tests
      run: |
        python manage.py test
